CREATE DATABASE hplussport;
GRANT ALL PRIVILEGES ON DATABASE hplussport TO postgres;


DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS salesperson;

DROP DATABASE IF EXISTS hplussport;
