CREATE DATABASE dungeonmanager;
GRANT ALL PRIVILEGES ON DATABASE dungeonmanager TO postgres;


DROP TABLE IF EXISTS dungeons;
DROP TABLE IF EXISTS rooms;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS customers;

DROP DATABASE IF EXISTS dungeonmanager;